modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="automachines"
version="1.0.0"
displayName="AutoMachines"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Maxim, MCreator"

[[dependencies.automachines]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



